import { BetGroupTeam, TeamName } from '@dzikimundial-ws/api-interfaces'

export const findTeam = (teamName: TeamName): BetGroupTeam =>
  teams.find((team: BetGroupTeam) => team.name === teamName) as BetGroupTeam

export const teams: BetGroupTeam[] = [
  {
    id: '0',
    description: 'Qatar',
    name: TeamName.QATAR,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1920px-Flag_of_Qatar.svg.png',
    position: 0,
    groupId: '0',
    group: 'A',
  },
  {
    id: '1',
    description: 'Ecuador',
    name: TeamName.ECUADOR,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1280px-Flag_of_Ecuador.svg.png',
    position: 1,
    groupId: '0',
    group: 'A',
  },
  {
    id: '2',
    description: 'Senegal',
    name: TeamName.SENEGAL,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1280px-Flag_of_Senegal.svg.png',
    position: 2,
    groupId: '0',
    group: 'A',
  },
  {
    id: '3',
    description: 'Netherlands',
    name: TeamName.NETHERLANDS,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png',
    position: 3,
    groupId: '0',
    group: 'A',
  },
  {
    id: '4',
    description: 'England',
    name: TeamName.ENGLAND,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/1920px-Flag_of_England.svg.png',
    position: 0,
    groupId: '0',
    group: 'B',
  },
  {
    id: '5',
    description: 'Iran',
    name: TeamName.IRAN,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/State_flag_of_Iran_%281964%E2%80%931980%29.svg/1920px-State_flag_of_Iran_%281964%E2%80%931980%29.svg.png',
    position: 1,
    groupId: '1',
    group: 'B',
  },
  {
    id: '6',
    description: 'USA',
    name: TeamName.USA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1920px-Flag_of_the_United_States.svg.png',
    position: 2,
    groupId: '1',
    group: 'B',
  },
  {
    id: '7',
    description: 'Wales',
    name: TeamName.WALES,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/1920px-Flag_of_Wales.svg.png',
    position: 3,
    groupId: '1',
    group: 'B',
  },
  {
    id: '8',
    description: 'Argentina',
    name: TeamName.ARGENTINA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1920px-Flag_of_Argentina.svg.png',
    position: 0,
    groupId: '2',
    group: 'C',
  },
  {
    id: '9',
    description: 'Saudi Arabia',
    name: TeamName.SAUDI_ARABIA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1280px-Flag_of_Saudi_Arabia.svg.png',
    position: 1,
    groupId: '2',
    group: 'C',
  },
  {
    id: '10',
    description: 'Mexico',
    name: TeamName.MEXICO,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.svg.png',
    position: 2,
    groupId: '2',
    group: 'C',
  },
  {
    id: '11',
    description: 'Poland',
    name: TeamName.POLAND,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Poland_%281927%E2%80%931980%29.svg/1920px-Flag_of_Poland_%281927%E2%80%931980%29.svg.png',
    position: 3,
    groupId: '2',
    group: 'C',
  },
  {
    id: '12',
    description: 'France',
    name: TeamName.FRANCE,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png',
    position: 0,
    groupId: '3',
    group: 'D',
  },
  {
    id: '13',
    description: 'Australia',
    name: TeamName.AUSTRALIA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1920px-Flag_of_Australia.svg.png',
    position: 1,
    groupId: '3',
    group: 'D',
  },
  {
    id: '14',
    description: 'Denmark',
    name: TeamName.DENMARK,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png',
    position: 2,
    groupId: '3',
    group: 'D',
  },
  {
    id: '15',
    description: 'Tunisia',
    name: TeamName.TUNISIA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1280px-Flag_of_Tunisia.svg.png',
    position: 3,
    groupId: '3',
    group: 'D',
  },
  {
    id: '16',
    description: 'Spain',
    name: TeamName.SPAIN,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg/1280px-Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg.png',
    position: 0,
    groupId: '4',
    group: 'E',
  },
  {
    id: '17',
    description: 'Costa Rica',
    name: TeamName.COSTA_RICA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/1920px-Flag_of_Costa_Rica_%28state%29.svg.png',
    position: 1,
    groupId: '4',
    group: 'E',
  },
  {
    id: '18',
    description: 'Germany',
    name: TeamName.GERMANY,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.svg.png',
    position: 2,
    groupId: '4',
    group: 'E',
  },
  {
    id: '19',
    description: 'Japan',
    name: TeamName.JAPAN,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/800px-Flag_of_Japan.svg.png',
    position: 3,
    groupId: '4',
    group: 'E',
  },
  {
    id: '20',
    description: 'Belgium',
    name: TeamName.BELGIUM,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1024px-Flag_of_Belgium.svg.png',
    position: 0,
    groupId: '5',
    group: 'F',
  },
  {
    id: '21',
    description: 'Canada',
    name: TeamName.CANADA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1920px-Flag_of_Canada_%28Pantone%29.svg.png',
    position: 1,
    groupId: '5',
    group: 'F',
  },
  {
    id: '22',
    description: 'Morocco',
    name: TeamName.MOROCCO,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1280px-Flag_of_Morocco.svg.png',
    position: 2,
    groupId: '5',
    group: 'F',
  },
  {
    id: '23',
    description: 'Croatia',
    name: TeamName.CROATIA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1920px-Flag_of_Croatia.svg.png',
    position: 3,
    groupId: '5',
    group: 'F',
  },
  {
    id: '24',
    description: 'Brazil',
    name: TeamName.BRAZIL,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png',
    position: 0,
    groupId: '6',
    group: 'G',
  },
  {
    id: '25',
    description: 'Serbia',
    name: TeamName.SERBIA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png',
    position: 1,
    groupId: '6',
    group: 'G',
  },
  {
    id: '26',
    description: 'Switzerland',
    name: TeamName.SWITZERLAND,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/1024px-Flag_of_Switzerland_%28Pantone%29.svg.png',
    position: 2,
    groupId: '6',
    group: 'G',
  },
  {
    id: '27',
    description: 'Cameroon',
    name: TeamName.CAMEROON,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1280px-Flag_of_Cameroon.svg.png',
    position: 3,
    groupId: '6',
    group: 'G',
  },
  {
    id: '28',
    description: 'Portugal',
    name: TeamName.PORTUGAL,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png',
    position: 0,
    groupId: '7',
    group: 'H',
  },
  {
    id: '29',
    description: 'Ghana',
    name: TeamName.GHANA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1280px-Flag_of_Ghana.svg.png',
    position: 1,
    groupId: '7',
    group: 'H',
  },
  {
    id: '30',
    description: 'Uruguay',
    name: TeamName.URUGUAY,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1280px-Flag_of_Uruguay.svg.png',
    position: 2,
    groupId: '7',
    group: 'H',
  },
  {
    id: '31',
    description: 'South Korea',
    name: TeamName.SOUTH_KOREA,
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1280px-Flag_of_South_Korea.svg.png',
    position: 3,
    groupId: '7',
    group: 'H',
  },
]
