import { Team } from '@dzikimundial-ws/api-interfaces'

export const teams: Team[] = [
  {
    id: '0',
    description: 'Qatar',
    name: 'QATAR',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1920px-Flag_of_Qatar.svg.png',
  },
  {
    id: '1',
    description: 'Ecuador',
    name: 'ECUADOR',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1280px-Flag_of_Ecuador.svg.png',
  },
  {
    id: '2',
    description: 'Senegal',
    name: 'SENEGAL',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1280px-Flag_of_Senegal.svg.png',
  },
  {
    id: '3',
    description: 'Netherlands',
    name: 'NETHERLANDS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png',
  },
  {
    id: '4',
    description: 'England',
    name: 'ENGLAND',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/1920px-Flag_of_England.svg.png',
  },
  {
    id: '5',
    description: 'Iran',
    name: 'IRAN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/State_flag_of_Iran_%281964%E2%80%931980%29.svg/1920px-State_flag_of_Iran_%281964%E2%80%931980%29.svg.png',
  },
  {
    id: '6',
    description: 'USA',
    name: 'USA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1920px-Flag_of_the_United_States.svg.png',
  },
  {
    id: '7',
    description: 'Wales',
    name: 'WALES',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/1920px-Flag_of_Wales.svg.png',
  },
  {
    id: '8',
    description: 'Argentina',
    name: 'ARGENTINA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1920px-Flag_of_Argentina.svg.png',
  },
  {
    id: '9',
    description: 'Saudi Arabia',
    name: 'SAUDI_ARABIA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1280px-Flag_of_Saudi_Arabia.svg.png',
  },
  {
    id: '10',
    description: 'Mexico',
    name: 'MEXICO',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.svg.png',
  },
  {
    id: '11',
    description: 'Poland',
    name: 'POLAND',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Poland_%281927%E2%80%931980%29.svg/1920px-Flag_of_Poland_%281927%E2%80%931980%29.svg.png',
  },
  {
    id: '12',
    description: 'France',
    name: 'FRANCE',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png',
  },
  {
    id: '13',
    description: 'Australia',
    name: 'AUSTRALIA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1920px-Flag_of_Australia.svg.png',
  },
  {
    id: '14',
    description: 'Denmark',
    name: 'DENMARK',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png',
  },
  {
    id: '15',
    description: 'Tunisia',
    name: 'TUNISIA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1280px-Flag_of_Tunisia.svg.png',
  },
  {
    id: '16',
    description: 'Spain',
    name: 'SPAIN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg/1280px-Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg.png',
  },
  {
    id: '17',
    description: 'Costa Rica',
    name: 'COSTA_RICA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/1920px-Flag_of_Costa_Rica_%28state%29.svg.png',
  },
  {
    id: '18',
    description: 'Germany',
    name: 'GERMANY',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.svg.png',
  },
  {
    id: '19',
    description: 'Japan',
    name: 'JAPAN',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/800px-Flag_of_Japan.svg.png',
  },
  {
    id: '20',
    description: 'Belgium',
    name: 'BELGIUM',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1024px-Flag_of_Belgium.svg.png',
  },
  {
    id: '21',
    description: 'Canada',
    name: 'CANADA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1920px-Flag_of_Canada_%28Pantone%29.svg.png',
  },
  {
    id: '22',
    description: 'Morocco',
    name: 'MOROCCO',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1280px-Flag_of_Morocco.svg.png',
  },
  {
    id: '23',
    description: 'Croatia',
    name: 'CROATIA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1920px-Flag_of_Croatia.svg.png',
  },
  {
    id: '24',
    description: 'Brazil',
    name: 'BRAZIL',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png',
  },
  {
    id: '25',
    description: 'Serbia',
    name: 'SERBIA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png',
  },
  {
    id: '26',
    description: 'Switzerland',
    name: 'SWITZERLAND',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/1024px-Flag_of_Switzerland_%28Pantone%29.svg.png',
  },
  {
    id: '27',
    description: 'Cameroon',
    name: 'CAMEROON',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1280px-Flag_of_Cameroon.svg.png',
  },
  {
    id: '28',
    description: 'Portugal',
    name: 'PORTUGAL',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png',
  },
  {
    id: '29',
    description: 'Ghana',
    name: 'GHANA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1280px-Flag_of_Ghana.svg.png',
  },
  {
    id: '30',
    description: 'Uruguay',
    name: 'URUGUAY',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1280px-Flag_of_Uruguay.svg.png',
  },
  {
    id: '31',
    description: 'South Korea',
    name: 'SOUTH_KOREA',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1280px-Flag_of_South_Korea.svg.png',
  },
]
