import { BetGroup } from "../models/bets-groups/bets-group.model";

export const groups: BetGroup[] = [
  {
    id: '0',
    name: 'Group A',
    teams: [
      {
        id: '0',
        description: 'Qatar',
        name: 'Qatar',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1920px-Flag_of_Qatar.svg.png',
        position: 0,
      },
      {
        id: '1',
        description: 'Ecuador',
        name: 'Ecuador',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/1280px-Flag_of_Ecuador.svg.png',
        position: 1,
      },
      {
        id: '2',
        description: 'Senegal',
        name: 'Senegal',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1280px-Flag_of_Senegal.svg.png',
        position: 2,
      },
      {
        id: '3',
        description: 'Netherlands',
        name: 'Netherlands',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/1280px-Flag_of_the_Netherlands.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '1',
    name: 'Group B',
    teams: [
      {
        id: '4',
        description: 'England',
        name: 'England',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_England.svg/1920px-Flag_of_England.svg.png',
        position: 0,
      },
      {
        id: '5',
        description: 'Iran',
        name: 'Iran',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/State_flag_of_Iran_%281964%E2%80%931980%29.svg/1920px-State_flag_of_Iran_%281964%E2%80%931980%29.svg.png',
        position: 1,
      },
      {
        id: '6',
        description: 'The United Stated',
        name: 'The United Stated',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/1920px-Flag_of_the_United_States.svg.png',
        position: 2,
      },
      {
        id: '7',
        description: 'Wales',
        name: 'Wales',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/1920px-Flag_of_Wales.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '2',
    name: 'Group C',
    teams: [
      {
        id: '8',
        description: 'Argentina',
        name: 'Argentina',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/1920px-Flag_of_Argentina.svg.png',
        position: 0,
      },
      {
        id: '9',
        description: 'Saudi Arabia',
        name: 'Saudi Arabia',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/1280px-Flag_of_Saudi_Arabia.svg.png',
        position: 1,
      },
      {
        id: '10',
        description: 'Mexico',
        name: 'Mexico',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/800px-Flag_of_Mexico.svg.png',
        position: 2,
      },
      {
        id: '11',
        description: 'Poland',
        name: 'Poland',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_Poland_%281927%E2%80%931980%29.svg/1920px-Flag_of_Poland_%281927%E2%80%931980%29.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '3',
    name: 'Group D',
    teams: [
      {
        id: '12',
        description: 'France',
        name: 'France',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/1280px-Flag_of_France.svg.png',
        position: 0,
      },
      {
        id: '13',
        description: 'Australia',
        name: 'Australia',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/1920px-Flag_of_Australia.svg.png',
        position: 1,
      },
      {
        id: '14',
        description: 'Denmark',
        name: 'Denmark',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/1280px-Flag_of_Denmark.svg.png',
        position: 2,
      },
      {
        id: '15',
        description: 'Tunisia',
        name: 'Tunisia',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/1280px-Flag_of_Tunisia.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '4',
    name: 'Group E',
    teams: [
      {
        id: '16',
        description: 'Spain',
        name: 'Spain',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg/1280px-Flag_of_Spain_%281785%E2%80%931873%2C_1875%E2%80%931931%29.svg.png',
        position: 0,
      },
      {
        id: '17',
        description: 'Costa Rica',
        name: 'Costa Rica',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/1920px-Flag_of_Costa_Rica_%28state%29.svg.png',
        position: 1,
      },
      {
        id: '18',
        description: 'Germany',
        name: 'Germany',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/800px-Flag_of_Germany.svg.png',
        position: 2,
      },
      {
        id: '19',
        description: 'Japan',
        name: 'Japan',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/800px-Flag_of_Japan.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '5',
    name: 'Group F',
    teams: [
      {
        id: '20',
        description: 'Belgium',
        name: 'Belgium',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/1024px-Flag_of_Belgium.svg.png',
        position: 0,
      },
      {
        id: '21',
        description: 'Canada',
        name: 'Canada',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/1920px-Flag_of_Canada_%28Pantone%29.svg.png',
        position: 1,
      },
      {
        id: '22',
        description: 'Morocco',
        name: 'Morocco',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/1280px-Flag_of_Morocco.svg.png',
        position: 2,
      },
      {
        id: '23',
        description: 'Croatia',
        name: 'Croatia',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/1920px-Flag_of_Croatia.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '6',
    name: 'Group G',
    teams: [
      {
        id: '24',
        description: 'Brazil',
        name: 'Brazil',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/1280px-Flag_of_Brazil.svg.png',
        position: 0,
      },
      {
        id: '25',
        description: 'Serbia',
        name: 'Serbia',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/1280px-Flag_of_Serbia.svg.png',
        position: 1,
      },
      {
        id: '26',
        description: 'Switzerland',
        name: 'Switzerland',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Flag_of_Switzerland_%28Pantone%29.svg/1024px-Flag_of_Switzerland_%28Pantone%29.svg.png',
        position: 2,
      },
      {
        id: '27',
        description: 'Cameroon',
        name: 'Cameroon',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/1280px-Flag_of_Cameroon.svg.png',
        position: 3,
      },
    ],
  },
  {
    id: '7',
    name: 'Group H',
    teams: [
      {
        id: '28',
        description: 'Portugal',
        name: 'Portugal',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/1280px-Flag_of_Portugal.svg.png',
        position: 0,
      },
      {
        id: '29',
        description: 'Ghana',
        name: 'Ghana',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/1280px-Flag_of_Ghana.svg.png',
        position: 1,
      },
      {
        id: '30',
        description: 'Uruguay',
        name: 'Uruguay',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/1280px-Flag_of_Uruguay.svg.png',
        position: 2,
      },
      {
        id: '31',
        description: 'South Korea',
        name: 'South Korea',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/1280px-Flag_of_South_Korea.svg.png',
        position: 3,
      },
    ],
  },
]
