module.exports = {
  projects: [
    '<rootDir>/apps/dzikimundial-ui',
    '<rootDir>/apps/api',
    '<rootDir>/libs/theme',
    '<rootDir>/libs/assets',
    '<rootDir>/libs/ui-nav-link',
    '<rootDir>/libs/ui-logo',
    '<rootDir>/libs/ui-icon-button',
    '<rootDir>/libs/ui-flag',
    '<rootDir>/libs/pipes/sort-array-by-key',
    '<rootDir>/libs/ui-button',
    '<rootDir>/libs/ui-tooltip',
    '<rootDir>/apps/dzikimundial-shell-ui',
    '<rootDir>/apps/dzikimundial-admin-ui',
    '<rootDir>/libs/services/notifications',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/ui-team-info',
    '<rootDir>/libs/ui-input',
    '<rootDir>/libs/utils',
    '<rootDir>/apps/api-e2e',
    '<rootDir>/libs/ui-progress-bar',
    '<rootDir>/libs/test-utils',
    '<rootDir>/libs/ui-message',
    '<rootDir>/libs/ui-validation-error',
  ],
}
